name: flutter_base_template
description: base template
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  fl_chart: ^0.69.2
  provider: ^6.1.2
  intl: ^0.19.0
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  json_annotation: ^4.9.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  flutter_colorpicker: ^1.1.0

  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
